version: "3.9"

services:
  backend:
    image: backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Add other backend env variables here
    networks:
      - app-network

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "3000:80"  # assuming Nginx serves frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
