spring:
  application:
    name: account-management-backend
  datasource:
    url: jdbc:h2:mem:account;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
jwt:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.YourExampleJWTHere